### PR TITLE
correct verbiage, remove features, add statblock

### PR DESCRIPTION
**Pull request by mlenser**

### CODE REVIEW

**Comment by symposion** [comment]
Hey Mark - Could you fix the failing test?  I have a protected branches turned on so I can't merge a broken build without unprotecting everything. 

Actually, can I make a suggestion - perhaps you *shouldn't* fix the failing test, but instead change the code. In the spirit of our discussion about the import commands the other day, I think there's an argument for keeping the old options as aliases - they're both shorter and consistent with what Kevin's original script (however incorrectly, from a 5e POV) has been doing for a while now. Also, personally I want my token actions to have names that are as short as possible, because I already end up with enough for the token bar to start wrapping sometimes, and most of my players are even worse off, using 1280 screens.

**Comment by mlenser** [comment]
Lets chat later. I had no idea how to run the tests.

I agree with adding a "saves" psuedonym for "saving throws" (which would label the button as "Saves") as the "Saves" word is used on occasion in 5e. Ability Checks however include all 6 abilities and all of the skills so they should be labeled as such. This is how they are labeled in the PHB (174), on the SRD, and on my sheet. The goal of the sheet is to match 5e's design. The script's goal should be the same.

Users can always rename actions if they find them to be too long.

**Comment by symposion** [comment]
You should just run "gulp" to do linting and testing before you commit.
I agree that we should match the 5e standard; I think that having a shorter option is a valuable piece of functionality, however.
> Users can always rename actions if they find them to be too long.
I seem to remember that argument not washing very well when I proposed it you the other day :-P Furthermore, in this case it would require users manually to edit every character they create, which is considerably more onerous that aliasing !shaped-import-monster to %shaped-monster once for evermore.

How about a compromise - we add an "Abilities' alias for AbilityChecks ? That's a bit shorter and it's still close to the 5e language - and after all this is only an alias.

**Comment by mlenser** [comment]
The "abilities" name is already used - for the abilities themselves (Str, Dex, Con, Int, Wis, Cha).

AbilChcks if you want a short version would work.

**Comment by symposion** [comment]
Ok, fine, that'll do. BTW you might be better off running 'gulp test lint' to avoid building the ShapedScripts.js file that is more likely to create conflicts on merge...

**Comment by mlenser** [comment]
kk I'll look at it later tonight.

**Pull request merged**
