### PR TITLE
changes based on sheet 4.2.1

### PR DESCRIPTION
**Pull request by mlenser**
Hey Lucian,

I tried to run the tests, but got "Cannot find module './ghToken.json'" so I can't verify that this doesn't break tests.
I think I caught all the old variables, but may have missed some.

There will also need to be a change of behavior in the auto-revert to not auto-revert when initiative or a skill rolls with advantage. That should only happen if they roll with advantage and the roll_setting is set appropriately.

Feel free to make the necessary changes to anything I did here.

### CODE REVIEW

**Comment by mlenser** [comment]
Added some more.

"newCharSettings" doesn't need to set default variables. This should actually be wiped out and each place that references this should check if the parameters exist or not.

Also I'm not sure that all places have access to "rollOptions", but I figure you can fix that if not. It really should all come from 1 definition.

**Comment by symposion** [comment]
Hi Mark,

I'll take a look at this tomorrow. I can't accept the PR because I need to make the changes to the underlying project at roll20-shaped-scripts (which is why you couldn't run the tests!) rather than here. This project really only exists for the purposes of submitting to roll20 1-click. I will make the changes manually and then close this.

**Comment by mlenser** [comment]
Ah, ya, it looks kind of compiled. I tried to find the base script, but couldn't.

**Comment by mlenser** [comment]
See https://github.com/symposion/roll20-shaped-scripts/pull/146

**Pull request closed without merging**
